### PR TITLE
[RELEASE-1.5] Use internal-encryption to deploy internal certificates automatically

### PR DESCRIPTION
**Pull request by nak3**
This patch cherr-pick the upstream commit https://github.com/knative-sandbox/net-kourier/commit/b9b1e8b9e5e22a9b01c98797dbe9ea0b890a9c7a.

### CODE REVIEW

**Comment by nak3** [comment]
This is same cherry-pick with https://github.com/openshift-knative/net-kourier/pull/23 but for 1.5.

**Comment by mgencur** [comment]
The "Verify Deps and Codegen" check says:
```
--- a/vendor/knative.dev/pkg/version/version.go
+++ b/vendor/knative.dev/pkg/version/version.go
@@ -33,7 +33,7 @@ const (
 	// NOTE: If you are changing this line, please also update the minimum kubernetes
 	// version listed here:
 	// https://github.com/knative/docs/blob/mkdocs/docs/snippets/prerequisites.md
-	defaultMinimumVersion = "v1.19.0"
+	defaultMinimumVersion = "v1.22.0"
 )
I suppose it's alright?
```

**Comment by nak3** [comment]
Yes, it is alright. We need to change the `defaultMinimumVersion = "v1.19.0"`.

**Pull request merged**
