### PR TITLE
[release-1.8] Add Kourier seccomp patch

### PR DESCRIPTION
**Pull request by nak3**
This patch adds Kourier seccomp patch.

/cherry-pick release-1.9
For main https://github.com/openshift-knative/net-kourier/pull/50

### CODE REVIEW

**Comment by nak3** [comment]
xref: https://github.com/openshift-knative/serving/pull/219

**Comment by nak3** [comment]
/cc @ReToCode @skonto 

https://github.com/openshift-knative/serverless-operator/pull/2000 verified the patch. One test is failing but due to another reason.

**Comment by skonto** [comment]
> One test is failing but due to another reason.

I see multiple failures which one verifies this?

**Comment by nak3** [comment]
Please refer to https://github.com/openshift-knative/serverless-operator/pull/2000#issue-1624567301

**Comment by nak3** [comment]
The github action verify was failed due another reason. I will fix it in the separated PR (because it should be cherry-picked.)
I verified it in https://github.com/openshift-knative/net-kourier/pull/51
Especially
* https://github.com/openshift-knative/net-kourier/pull/51/commits/53edc13a06b3f050d53fe5aacc29f95c5e43e86e
* https://github.com/openshift-knative/net-kourier/pull/51/commits/85901e98dcbb13f3df2e9d3eef5f4ce63aee78b3
* https://github.com/openshift-knative/net-kourier/pull/51/commits/f79f0a1ca48d39d83f01ff4adfe15bc163ecac16

**Comment by nak3** [comment]
I will fix the verify in separated PR and https://github.com/openshift-knative/net-kourier/pull/51 should be merged before this to avoid confusion.
/hold

**Comment by skonto** [comment]
> Please refer to https://github.com/openshift-knative/serverless-operator/pull/2000#issue-1624567301

What about this: https://github.com/openshift-knative/serverless-operator/pull/2000#issuecomment-1469727007?
I would expect the S-O PR to pass.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Comment by nak3** [comment]
I will cherry-pick it manually once verify patches were merged.

**Pull request merged**
