### PR TITLE
[SRVKS-946] Setup xds keep alive

### PR DESCRIPTION
**Pull request by skonto**
* Setting keep alive for the ADS cluster. 
* This is in alignment with [envoy recommendations](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol#aggregated-discovery-service).
* Defaults seem [too high](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/core/v3/address.proto#config-core-v3-tcpkeepalive).
* Behavior on keep alive failure detection is re connection.

### CODE REVIEW

**Comment by nak3** [comment]
I think we should introduce an temporary option in operator (e.g. annotation to switch this configuration) which allows users to switch back to the current default. Then, we can drop the configuration after the several release if there is no issue.

**Comment by maschmid** [comment]
The recommendation says
> It is recommended to configure either HTTP/2 or TCP keepalives

I could try if just enabling the HTTP/2 keepalives as in the example would be enough (for the cases which we can reproduce)

**Comment by skonto** [comment]
@maschmid re-using what is in the docs makes sense assuming we have time to test it anyway. You have already tested the other settings.

**Comment by skonto** [comment]
> I think we should introduce an temporary option in operator (e.g. annotation to switch this configuration) which allows users to switch back to the current default. Then, we can drop the configuration after the several release if there is no issue.

That requires documentation work not sure we can do for 1.25.

**Comment by nak3** [comment]
> Do you think we require some options at the net-kourier xds server side for grpc timeouts?

I agree if we will allow users to configure the options but I am not so positive if we will change the default values a lot. For now, I think we should apply the _minimum_ change which was verified by Marek.

And if you haven't started the configuration option via operator to change the bootstrap, shall I do that?

**Comment by maschmid** [comment]
@skonto 

It seems to be working fine with just

```
          http2_protocol_options:
            connection_keepalive:
              interval: 30s
              timeout: 5s
```

**Comment by skonto** [comment]
@nak3 let's do the http one. Would you mind taking over on this one for 1.26?

**Comment by skonto** [comment]
Closing in favor of https://github.com/openshift-knative/net-kourier/pull/33

**Pull request closed without merging**
