### PR TITLE
[CP] Graceful shutdown

### PR DESCRIPTION
**Pull request by nak3**
This patch backport https://github.com/knative/net-kourier/commit/e9e16bcbc60b1b3771320164c6606e007576b2cd to release-0.13 branch for https://issues.redhat.com/browse/SRVKS-570.

### CODE REVIEW

**Comment by nak3** [comment]
/hold

Although I agreed to backport this fix, it contains envoy image's update to `docker.io/maistra/proxyv2-ubi8:1.1.0`. Is it alright to backport it?

/cc @markusthoemmes @warrenvw @jmprusi

**Comment by nak3** [comment]
(Note, as per @jmprusi 's comment on slack, we have to update the envoy image to backport this fix.)

**Comment by markusthoemmes** [comment]
@nak3 would you please send the same to the 0.14 branch?

**Comment by nak3** [comment]
Sure, sent it here https://github.com/openshift-knative/net-kourier/pull/3

**Comment by nak3** [comment]
This is backported to v1.8. We will not backport to 1.7 (based on knative serving v0.13.)

**Pull request closed without merging**
