### PR TITLE
[RELEASE-1.9] [SRVKS-1046] Add missing probes 

### PR DESCRIPTION
**Pull request by skonto**
As in https://github.com/openshift-knative/net-kourier/pull/56.

### CODE REVIEW

**Review by ReToCode — APPROVED** [review]
/lgtm

**Comment by nak3** [comment]
This is a configuration/manifest change so `openshift/release/artifacts/0-kourier.yaml` should have been updated.
(https://github.com/openshift-knative/net-kourier/pull/56 as well.)

**Comment by ReToCode** [comment]
> This is a configuration/manifest change so openshift/release/artifacts/0-kourier.yaml should have been updated.
(https://github.com/openshift-knative/net-kourier/pull/56 as well.)

:( You are right, we missed it again. I think this could be another good idea for a GH-action. Can we run the script and check if there are diffs on each PR?

**Comment by ReToCode** [comment]
Jira to track it: https://issues.redhat.com/browse/SRVKS-1060
I'll update the manifests in a followup PR.

**Pull request merged**
