### PR TITLE
[SRVKS-1170][release-v1.11] Increase Kourier Gateway CPU limit instead of controller

### PR DESCRIPTION
**Pull request by nak3**
This patch cherry-pick 1a0457fadac77b9993ff8ba9500741bec3fb2ba0

### CODE REVIEW

**Comment by ReToCode** [comment]
We do need to update the artefacts in `openshift` as well, right?

**Comment by nak3** [comment]
Thank you! I missed it. updated.

**Review by ReToCode — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
