### PR TITLE
[release-v1.10] Define knative-serving-ingress for Kourier Gateway xdp client

### PR DESCRIPTION
**Pull request by nak3**
This patch is same with https://github.com/openshift-knative/net-kourier/pull/89 but against 1.10.

### CODE REVIEW

**Comment by nak3** [comment]
For `Verify / verify / Verify Deps and Codegen (pull_request)`, we need to ignore the error as we(downstream) added the [patch](https://github.com/openshift-knative/net-kourier/blob/release-v1.10/openshift/patches/003-pqs-burst.patch) under `vendor`  directory. (It will be dropped after 1.11.) Upstream's verify action complains about it.

**Review by ReToCode — APPROVED** [review]
/lgtm

**Comment by nak3** [comment]
/override "Verify / verify / Verify Deps and Codegen"

**Comment by nak3** [comment]
/override "verify / Verify Deps and Codegen"

**Pull request merged**
